### ISSUE TITLE
Tracking issue for API v10

### ISSUE THREAD

**Issue by shiftinv** [DisnakeDev/disnake#351]
see https://github.com/discord/discord-api-docs/discussions/4510

v9 will be deprecated as of 2022-04-30, and decommissioned at least one year later.

Changes between v9 and v10:
- [ ] Specifying the message content intent (`1 << 15`) is required, v9 will automatically receive message content intent if application is approved for it #353 
- [x] `application.summary` is deprecated, will be removed in v11 -- deprecated with #369 
- [x] ~~Achievement localization format has changed~~ not relevant
- [x] ~~`/channels/<channel_id>/threads/active` has been removed~~ not implemented
- [x] Existing `attachments` must be specified when `PATCH`ing messages with new attachments
    - should already be implemented, see #100 + #335
- [x] `reason` as a body/query parameter is no longer supported, should instead use the `X-Audit-Log-Reason` header
    - should already be implemented, remaining occurrences removed in #266
- [x] Message routes accept `embeds` rather than `embed`
- [x] Requests to v10 and higher will no longer be supported on `discordapp.com`

**Comment by onerandomusername** [comment]
They didn't supply all breaking changes in the changelog.

Not mentioned (that I know of so far):
- requiring type be passed to thread create
